### ISSUE TITLE
Excel Report Execution Role UI

### ISSUE THREAD

**Issue by terrypacker** [infiniteautomation/ma-modules-public#124]
I added a new field to the excel report templates that control the permission holder's roles when the report is run.  This effects what points/events can be accessed and what roles the scripts run with.

The model field is:

```
reportExecutionRoles: ['rolexid1',rolexid2'...]
```

**Comment by jazdw** [comment]
- What happens when the user has access to DP_XYZ and adds it to a report but doesn't give the report the role required to access DP_XYZ?
- What happens when the user has access to DP_XYZ and adds it to a report which is emailed to themselves, then later an admin revokes their ability to see DP_XYZ?

**Comment by jazdw** [comment]
Fixed via infiniteautomation/ma-modules-proprietary@755e0496b15433a224b09b716ef489a323286cf7
